name: Firebase Continuous Deployment

on:
  push:
    branches: ['master']
jobs:
   build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      env:
        HOST: all.rit.edu
        USERNAME: all
        PORT: 22
        KEY: ${{ secrets.SSH_SECRET }}
      with:
        source: "deploy.tar"
        target: "research/AccessibilityLab1/"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: all.rit.edu
        USERNAME: all
        KEY: ${{ secrets.SSH_SECRET }}
        PORT: 22
        script: |
          cd research/AccessibilityLab1
          npm install
          npm run-script build

