name: Continuous Deployment

on:
  push:
    branches: ['master']
jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        HOST: all.rit.edu
        USERNAME: all
        PORT: 22
        KEY: ${{ secrets.SSH_SECRET }}
        source: "."
        target: "/home/all/research/"
    - name: remote ssh commands
      uses: fifsky/ssh-action@master
      with:
        command: |
          chmod -R g+w research
          cd research/client
          cd ../server
          tmux kill-server 
          tmux new-session -s all
        args: "-tt"
        host: all.rit.edu
        user: all
        key: ${{ secrets.SSH_SECRET }}
